version: "3.7"
services:
  db:
    image: postgres:14.2
    container_name: ing_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ing
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: ing_zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: ing_kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: ing_zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER_NETWORK://ing_kafka:29092,LISTENER_DOCKER_HOST://ing_kafka:9092,LISTENER_LOCAL_KAFKA://127.0.0.1:12345
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_NETWORK://ing_kafka:29092,LISTENER_DOCKER_HOST://127.0.0.1:9092,LISTENER_LOCAL_KAFKA://127.0.0.1:12345
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_NETWORK:PLAINTEXT,LISTENER_DOCKER_HOST:PLAINTEXT,LISTENER_LOCAL_KAFKA:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_NETWORK
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "TrainingTopic:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    ports:
#      - "9000:9000"
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_BROKERCONNECT: "user_kafka:29092"
#      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
